# Generated by Django 4.2.16 on 2024-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0007_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('sports', 'Sports')], default='tech', max_length=50),
        ),
    ]
