# Generated by Django 4.2.16 on 2024-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Lifestyle', 'Lifestyle'), ('Education', 'Education'), ('Sports', 'Sports')], default='tech', max_length=50),
        ),
    ]
